name: Cargo Test
on:
  push:
    branches:
      - *
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  RUST_LOG: ${{ vars.RUST_LOG }}
  TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
  TEST_RPC_URL: ${{ secrets.TEST_RPC_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Build
        run: |
          # ambiguous-glob-reexports is allowed due to abigen code. 
          export RUSTFLAGS="-D warnings -A ambiguous-glob-reexports"
          cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
